spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
javabackend.jwt.base64-secret=${JWT_SECRET_BASE64}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=false
app.bootstrap.admin.enabled=false
app.devops.seeding.enabled=false
