spring.main.web-application-type=none
spring.flyway.enabled=true
spring.flyway.validate-on-migrate=true
spring.jpa.hibernate.ddl-auto=none
app.bootstrap.admin.enabled=false
app.devops.seeding.enabled=false
