package com.web_tutorial.javabackend.observability;

public enum SecurityAuditEvent {
    AUTH_LOGIN_SUCCEEDED,
    AUTH_LOGIN_FAILED,
    AUTH_LOGIN_THROTTLED,
    AUTH_REGISTER_SUCCEEDED,
    AUTH_REGISTER_REJECTED,
    AUTH_REFRESH_SUCCEEDED,
    AUTH_REFRESH_FAILED,
    AUTH_REFRESH_REUSE_DETECTED,
    AUTH_LOGOUT_SUCCEEDED,
    AUTHZ_ACCESS_DENIED,
    AUTHZ_IDOR_ATTEMPT,
    AUTHZ_ROLE_ESCALATION_REJECTED,
    ADMIN_USER_CREATED,
    ADMIN_USER_UPDATED,
    ADMIN_USER_DELETED,
    ADMIN_ROLE_CHANGED,
    ADMIN_CONTENT_CREATED,
    ADMIN_CONTENT_UPDATED,
    ADMIN_CONTENT_DELETED,
    UPLOAD_SUCCEEDED,
    UPLOAD_REJECTED,
    UPLOAD_RATE_LIMITED,
    INPUT_VALIDATION_REJECTED,
    RATE_LIMIT_TRIGGERED
}
